server {
    listen 80;
    server_name flowsctrl.com;

    # Snippets y Auth
    include /etc/nginx/snippets/authelia.conf;

    # Login de Authelia
    location /api/auth/ {
        proxy_pass http://infra-authelia-1:9091/;
        proxy_set_header Host $host;
        proxy_set_header X-Original-URL $scheme://$http_host$request_uri;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Dashboard Principal
    location / {
        auth_request /authelia/auth;
        error_page 401 =302 https://flowsctrl.com/api/auth/?rd=$scheme://$host$request_uri;

        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}