server {
    listen 80;
    server_name flowsctrl.com www.flowsctrl.com;

    # Importante: Nombre correcto del contenedor para auth
    include /etc/nginx/snippets/authelia.conf;

    location / {
        auth_request /authelia/auth;
        # Redirección al login público si no hay sesión
        error_page 401 =302 https://flowsctrl.com/api/auth/?rd=$scheme://$host$request_uri;

        root /usr/share/nginx/html;
        index index.html;
    }

    location /api/auth/ {
        proxy_pass http://infra-authelia-1:9091/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}