theme: dark

server:
  address: tcp://0.0.0.0:9091

log:
  level: info

totp:
  issuer: "TuServidor"

authentication_backend:
  file:
    path: /config/users.yml

access_control:
  default_policy: deny
  rules:
    - domain: "flowsctrl.com"
      policy: bypass
      resources:
        - "^/api/auth/.*$"
    - domain: "flowsctrl.com"
      policy: one_factor
      resources:
        - "^/$"
    - domain: "flowsctrl.com"
      policy: two_factor
      resources:
        - "^/apps/.*$"




session:
  name: authelia_session
  secret: "ae699e77a8bb1bc7b50cccb715d047013db46466ede67f2277e502242f40b4c5"
  cookies:
    - domain: "flowsctrl.com"
      authelia_url: "https://flowsctrl.com"
  redis:
    host: redis
    port: 6379

storage:
  encryption_key: "48af27386359ace16932da0f1813e79fc6b8eda70aa0728c0abbe7342dec12e8"
  local:
    path: /config/db.sqlite3

notifier:
  filesystem:
    filename: /config/notification.txt

identity_validation:
  reset_password:
    disable: true
