theme: dark

server:
  address: tcp://0.0.0.0:9091

log:
  level: info

totp:
  issuer: "TuServidor"

authentication_backend:
  file:
    path: /config/users.yml

access_control:
  default_policy: deny
  rules:
    - domain: "flowsctrl.com"
      policy: bypass
      resources:
        - "^/api/auth/.*$"
    - domain: "flowsctrl.com"
      policy: one_factor
      resources:
        - "^/$"
    - domain: "flowsctrl.com"
      policy: two_factor
      resources:
        - "^/apps/.*$"

session:
  name: authelia_session
  # Este es el secreto de la sesión (ya lo tenías)
  secret: "ae699e77a8bb1bc7b50cccb715d047013db46466ede67f2277e502242f40b4c5"
  cookies:
    - domain: "flowsctrl.com"
      authelia_url: "https://flowsctrl.com"
  redis:
    host: infra-redis-1  # Ajustado al nombre de tu contenedor
    port: 6379

storage:
  encryption_key: "48af27386359ace16932da0f1813e79fc6b8eda70aa0728c0abbe7342dec12e8"
  local:
    path: /config/db.sqlite3

notifier:
  filesystem:
    filename: /config/notification.txt

identity_validation:
  reset_password:
    disable: true
    # AÑADE ESTA LÍNEA (Es obligatoria por seguridad interna de Authelia)
    jwt_secret: "a2b3c4d5e6f7g8h9i0j1k2l3m4n5o6p7q8r9s0t1u2v3w4x5y6z"