theme: dark

server:
  address: tcp://0.0.0.0:9091

log:
  level: info

totp:
  issuer: "TuServidor"

authentication_backend:
  file:
    path: /config/users.yml

access_control:
  default_policy: deny
  rules:
    - domain: "flowsctrl.com"
      policy: one_factor
      resources:
        - "^/$"
        - "^/dashboard/?$"
    - domain: "flowsctrl.com"
      policy: two_factor
      resources:
        - "^/apps/.*$"

session:
  name: authelia_session
  secret: "CAMBIA_ESTO_POR_UN_SECRETO_LARGO"
  cookies:
    - domain: "flowsctrl.com"
      authelia_url: "https://flowsctrl.com"
  redis:
    host: redis
    port: 6379

storage:
  encryption_key: "CAMBIA_ESTO_POR_OTRO_SECRETO_LARGO"
  local:
    path: /config/db.sqlite3

notifier:
  filesystem:
    filename: /config/notification.txt

identity_validation:
  reset_password:
    disable: true
