users:
  ignacio:
    displayname: "Ignacio"
    # Pega aquí el hash completo que generaste en el paso anterior
    password: "2WMPN26W6rr.," 
    email: "ignacio@flowsctrl.com"
    groups:
      - admins
      - users




      